Coursework: BMP Class Reference
BMP Class Reference
Класс для работы с изображениями в формате BMP.
#include <bmp.h>
Public Member Functions
BMP (const std::string &fileName)
Конструктор класса BMP.
void getInfo () const
Получить информацию о изображении.
void mirror (const std::string &axis, const Coordinate &left_up, const Coordinate &right_down)
Отразить изображение относительно указанной оси.
void save (const std::string &fileName)
Сохранить изображение в файл.
bool isValid () const
Проверить, является ли изображение валидным.
void copy (const Coordinate &src_left_up, const Coordinate &src_right_down, const Coordinate &dest_left_up)
Копировать область изображения.
void colorReplace (const RGB &old_color, const RGB &new_color)
Заменить цвет на изображении.
void split (int number_x, int number_y, int thickness, const RGB &color)
Разделить изображение на части.
Detailed Description
Класс для работы с изображениями в формате BMP.
Definition at line 15 of file bmp.h.
Constructor & Destructor Documentation
BMP()
BMP::BMP (const std::string & fileName)
Конструктор класса BMP.
Parameters
fileName Путь к файлу изображения.
Definition at line 15 of file bmp.cpp.
Member Function Documentation
getInfo()
void BMP::getInfo () const
Получить информацию о изображении.
Вывод информации о заголовке BMP-изображения.
Definition at line 303 of file bmp.cpp.
Referenced by main().
mirror()
void BMP::mirror (const std::string & axis, const Coordinate & left_up, const Coordinate & right_down)
Отразить изображение относительно указанной оси.
Отражение изображения по горизонтали или вертикали.
Parameters
axis Ось отражения ("x" или "y").
left_up Координаты левого верхнего угла области отражения.
right_down Координаты правого нижнего угла области отражения.
Definition at line 149 of file bmp.cpp.
Referenced by main().
save()
void BMP::save (const std::string & fileName)
Сохранить изображение в файл.
Сохранение изображения в файл.
Parameters
fileName Имя файла для сохранения изображения.
Definition at line 273 of file bmp.cpp.
Referenced by main().
isValid()
bool BMP::isValid () const
Проверить, является ли изображение валидным.
Проверка наличия данных изображения в объекте BMP.
Returns
true, если изображение валидно, иначе false.
true, если в объекте есть данные изображения, в противном случае - false.
Definition at line 84 of file bmp.cpp.
Referenced by main().
copy()
void BMP::copy (const Coordinate & src_left_up, const Coordinate & src_right_down, const Coordinate & dest_left_up)
Копировать область изображения.
Копирование области изображения.
Parameters
src_left_up Координаты левого верхнего угла исходной области.
src_right_down Координаты правого нижнего угла исходной области.
dest_left_up Координаты левого верхнего угла целевой области.
Definition at line 234 of file bmp.cpp.
Referenced by main().
colorReplace()
void BMP::colorReplace (const RGB & old_color, const RGB & new_color)
Заменить цвет на изображении.
Замена цвета пикселей на изображении.
Parameters
old_color Старый цвет.
new_color Новый цвет.
Definition at line 129 of file bmp.cpp.
Referenced by main().
split()
void BMP::split (int number_x, int number_y, int thickness, const RGB & color)
Разделить изображение на части.
Создание разделительных линий на изображении.
Parameters
number_x Количество частей по горизонтали.
number_y Количество частей по вертикали.
thickness Толщина разделительных линий.
color Цвет разделительных линий.
Definition at line 193 of file bmp.cpp.
Referenced by main().
The documentation for this class was generated from the following files:
include/bmp.h
src/bmp.cpp