Coursework: Logger Class Reference
Logger Class Reference
Класс для записи логов.
#include <logger.h>
Static Public Member Functions
static void setColorsEnabled (bool enableColors)
Устанавливает разрешение использования цветов в выводе.
static void log (const std::string &message)
Записывает сообщение в лог.
static void warn (const std::string &message)
Записывает предупреждение в лог.
static void error (const std::string &message)
Записывает ошибку в лог.
static void exit (const int exitCode, const std::string &exitMessage)
Записывает сообщение и завершает программу с заданным кодом выхода.
Detailed Description
Класс для записи логов.
Definition at line 9 of file logger.h.
Member Function Documentation
setColorsEnabled()
void Logger::setColorsEnabled (bool enableColors) static
Устанавливает разрешение использования цветов в выводе.
Установить использование цветов для логирования.
Parameters
enableColors true, если цвета разрешены, false в противном случае.
Definition at line 18 of file logger.cpp.
Referenced by parseCommandLine().
log()
void Logger::log (const std::string & message) static
Записывает сообщение в лог.
Залогировать сообщение в консоль.
Parameters
message Сообщение для записи в лог.
Definition at line 27 of file logger.cpp.
Referenced by displayHelp(), BMP::getInfo(), and main().
warn()
void Logger::warn (const std::string & message) static
Записывает предупреждение в лог.
Залогировать предупреждение в консоль.
Parameters
message Сообщение предупреждения для записи в лог.
Definition at line 43 of file logger.cpp.
Referenced by BMP::copy(), main(), parseCommandLine(), and BMP::split().
error()
void Logger::error (const std::string & message) static
Записывает ошибку в лог.
Залогировать сообщение об ошибке в консоль.
Parameters
message Сообщение ошибки для записи в лог.
Definition at line 58 of file logger.cpp.
Referenced by exit().
exit()
void Logger::exit (const int exitCode, const std::string & exitMessage) static
Записывает сообщение и завершает программу с заданным кодом выхода.
Залогировать сообщение об ошибке и завершить программу с указанным кодом завершения.
Parameters
exitCode Код выхода.
exitMessage Сообщение о завершении программы.
Definition at line 73 of file logger.cpp.
Referenced by BMP::BMP(), BMP::copy(), main(), BMP::mirror(), parseCommandLine(), parseRGB(), and BMP::save().
The documentation for this class was generated from the following files:
include/logger.h
src/logger.cpp