Coursework: src/operation_params.cpp File Reference
operation_params.cpp File Reference
Этот файл содержит реализацию основного функционала.
#include "operation_params.h"
#include "logger.h"
#include "messages.h"
#include <algorithm>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>
Functions
std::vector< int > parseValues (const std::string &str)
Разбирает значения из строки, разделенной точками, и сохраняет их в векторе.
RGB parseRGB (const std::string &str)
Разбирает строку, представляющую цвет RGB, в структуру RGB.
void displayHelp ()
Отображает справку.
OperationParams parseCommandLine (int argc, char *argv[])
Разбирает аргументы командной строки и возвращает объект OperationParams.
Detailed Description
Этот файл содержит реализацию основного функционала.
Definition in file operation_params.cpp.
Function Documentation
parseValues()
std::vector<int> parseValues (const std::string & str)
Разбирает значения из строки, разделенной точками, и сохраняет их в векторе.
Парсинг строки с числами, разделенными пробелами.
Parameters
str Входная строка, содержащая значения, разделенные точками.
Returns
Вектор, содержащий разобранные целочисленные значения.
Definition at line 21 of file operation_params.cpp.
Referenced by parseCommandLine(), and parseRGB().
parseRGB()
RGB parseRGB (const std::string & str)
Разбирает строку, представляющую цвет RGB, в структуру RGB.
Парсинг строки с RGB-значением цвета.
Parameters
str Входная строка, представляющая цвет RGB.
Returns
Структура RGB, представляющая разобранный цвет.
Exceptions
std::invalid_argument если формат цвета неверен.
Definition at line 37 of file operation_params.cpp.
Referenced by parseCommandLine().
displayHelp()
void displayHelp ()
Отображает справку.
Отображение справки о возможных параметрах командной строки.
Definition at line 54 of file operation_params.cpp.
Referenced by parseCommandLine().
parseCommandLine()
OperationParams parseCommandLine (int argc, char * argv[])
Разбирает аргументы командной строки и возвращает объект OperationParams.
Парсинг командной строки и создание объекта OperationParams.
Parameters
argc Количество аргументов командной строки.
argv Массив строк аргументов командной строки.
Returns
Разобранный объект OperationParams.
Definition at line 82 of file operation_params.cpp.
Referenced by main().