Coursework: include/operation_params.h File Reference
operation_params.h File Reference
Определяет функции для анализа параметров операций из командной строки.
#include "structures.h"
#include <string>
#include <vector>
Functions
OperationParams parseCommandLine (int argc, char *argv[])
Парсинг командной строки и создание объекта OperationParams.
std::vector< int > parseValues (const std::string &str)
Парсинг строки с числами, разделенными пробелами.
RGB parseRGB (const std::string &str)
Парсинг строки с RGB-значением цвета.
void displayHelp ()
Отображение справки о возможных параметрах командной строки.
Detailed Description
Определяет функции для анализа параметров операций из командной строки.
Definition in file operation_params.h.
Function Documentation
parseCommandLine()
OperationParams parseCommandLine (int argc, char * argv[])
Парсинг командной строки и создание объекта OperationParams.
Parameters
argc Количество аргументов командной строки.
argv Массив строк, содержащих аргументы командной строки.
Returns
OperationParams объект, содержащий параметры операции.
Парсинг командной строки и создание объекта OperationParams.
Returns
Структура параметров операции.
Definition at line 84 of file operation_params.cpp.
Referenced by main().
parseValues()
std::vector<int> parseValues (const std::string & str)
Парсинг строки с числами, разделенными пробелами.
Parameters
str Строка, содержащая числа, разделенные пробелами.
Returns
Вектор целых чисел, полученных из строки.
Парсинг строки с числами, разделенными пробелами.
Returns
Вектор целочисленных значений, полученных из строки.
Definition at line 20 of file operation_params.cpp.
Referenced by parseCommandLine(), and parseRGB().
parseRGB()
RGB parseRGB (const std::string & str)
Парсинг строки с RGB-значением цвета.
Parameters
str Строка, содержащая RGB-значение цвета в формате "R,G,B".
Returns
Структура RGB, представляющая цвет.
Парсинг строки с RGB-значением цвета.
Returns
Структура RGB, содержащая значения красного, зеленого и синего каналов.
Definition at line 36 of file operation_params.cpp.
Referenced by parseCommandLine().
displayHelp()
void displayHelp ()
Отображение справки о возможных параметрах командной строки.
Отображение справки о возможных параметрах командной строки.
Definition at line 57 of file operation_params.cpp.
Referenced by parseCommandLine().